"""empty message

Revision ID: 9cfd18c29e3d
Revises: 
Create Date: 2023-12-29 13:03:59.765674

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9cfd18c29e3d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('book_info',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=32), nullable=False),
    sa.Column('author', sa.String(length=32), nullable=False),
    sa.Column('create_date', sa.DateTime(), nullable=False),
    sa.Column('answer', sa.String(length=400), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('fcuser',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('password', sa.String(length=64), nullable=True),
    sa.Column('userid', sa.String(length=32), nullable=True),
    sa.Column('username', sa.String(length=8), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('fcuser')
    op.drop_table('book_info')
    # ### end Alembic commands ###
